define(["angular", "jquery", "fancybox", "tiledGallery"], function() {
'use strict';

  angular.module('myApp.directives', [])

  	.directive('tiledGallery', function($http){
      return {
      	// restrict to element name: <tiled-gallery></tiled-gallery>
        restrict: 'C',
        // This HTML will replace the tiledGallery directive.
        replace: true,
        transclude: true,
        template: '',
        
        // The linking function will add behavior to the template
        link: function(scope, element, attrs) {
            var template;
            var tiledGalleryWidth = $('.main-content').width();

            // NOTES: To debug potential Photo PHP issues:
            // 1. tile-gallery-init.php is served either on local apache-php-enabled server or via Heroku PHP server at http://my-ptflo.herokuapp.com
            // 2. Photos that tiled-gallery-init.php uses will be on 
            //     a. locally: /srv/www/apache/gitrepos/wil-ng/img/photos
            //     b. remotely on heroku: http://my-ptflo.herokuapp.com/wil-ng/app/img/photos/sf-w480.jpg
            // 3. DEBUG by going to https://my-ptflo.herokuapp.com/js/lib/tiled-gallery/tiled-gallery-init.php to see if tiled gallery photo's display;
            // if not, then the remote php server is not running

            // set siteRootUrl = https://localhost/gitrepos/wil-ng, if running wil-ng locally
            // set siteRootUrl = https://my-ptflo.herokuapp.com, if running wil-ng deployed on heroku
            var siteRootUrl = window.location.href.replace('/#/photos','');
            //console.log('siteRootUrl=' + siteRootUrl);
           
            var photoTiledGalleryUrl = siteRootUrl + '/js/lib/tiled-gallery/tiled-gallery-init.php';
            //console.log('photoTiledGalleryUrl=' + photoTiledGalleryUrl);
                               
            // pass into the php the initial gallery width so that images can be sized properly
            // without having to call TiledGalleryInstance.resize();              
            $http({method: 'GET', url: photoTiledGalleryUrl,  params: {site_root_url: siteRootUrl, gallery_width: tiledGalleryWidth}}).          
            ////$http({method: 'GET', url: 'https://my-ptflo.herokuapp.com/js/lib/tiled-gallery/tiled-gallery-init.php',  params: {gallery_width: tiledGalleryWidth}}).
            ////$http({method: 'GET', url: '//p.wilyan.com/js/lib/tiled-gallery/tiled-gallery-init.php',  params: {gallery_width: tiledGalleryWidth}}).
  		      ////$http({method: 'GET', url: '//ng-wilyan.rhcloud.com/app/js/lib/tiled-gallery/tiled-gallery-init.php',  params: {gallery_width: tiledGalleryWidth}}).
  			
  		      success(function(data, status, headers, config) {
  		           template = data;
  		           element.append(template);

  		           // after loading the tiled gallery HTML generated by tiled-gallery-init.php,
  		           // intiallize the tiled gallery in tiled-gallery.js
  		           var TiledGalleryInstance = new TiledGallery;
  		           $(".fancybox").fancybox();

  		      }).
  		      error(function(data, status, headers, config) {
  		           // called asynchronously if an error occurs
  			       // or server returns response with an error status.
  		      });

        }
      }
  	}
  );
});
